apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "patient-api.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: patient-api
