apiVersion: v1
kind: Namespace
metadata:
  name: patient-api
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: clinical-integration
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: event-worker
  labels:
    pod-security.kubernetes.io/enforce: restricted
