apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: careflow-patient-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/careflow-multiregion-platform.git
    targetRevision: main
    path: helm/patient-api
  destination:
    server: https://kubernetes.default.svc
    namespace: patient-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
